[package]
name = "telio-wireguard-traceroute"
version = "0.0.2"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
base64 = "0.22.1"
blake2 = "0.10.6"
clap = { version = "4.5.51", features = ["derive", "env"] }
dns-lookup = "3.0.1"
env_logger = "0.11.8"
hex = "0.4.3"
hmac = "0.12.1"
log = "0.4.28"
pnet_packet = "0.35.0"
rand = "0.9.2"
snow = "0.10.0"
socket2 = { version = "0.6.1", features = ["all"] }
tokio = { version = "1.48.0", features = ["bytes", "fs", "full", "io-std", "io-util", "macros", "net", "time", "tokio-macros"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_Networking_WinSock",
    "Win32_System_IO",
] }
